spring:
  thymeleaf:
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${OAUTH2_GOOGLE_URI}
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
            scope:
              - profile
              - email
      password: ${OAUTH2_PASSWORD}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    database: oracle

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    yj.board: DEBUG
    org.hibernate:
      type:
        descriptor.sql: TRACE

jwt:
  header: Authorization
  refresh-token-header: RefreshToken
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 604800

server:
  port: 8443
  ssl:
    key-store: ${SSL_KEY_STORE}
    key-store-type: ${SSL_KEY_STORE_TYPE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}

mybatis:
  type-aliases-package: yj.board.domain
  configuration:
    map-underscore-to-camel-case: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      s3url-temp: ${AWS_S3_BUCKET_URL_TEMP}
      s3url: ${AWS_S3_BUCKET_URL}
