spring:

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: test2
    password: test2
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    database: oracle

  sql:
    init:
      mode: always

logging:
  level:
    yj.board: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
#  issuer: ajufresh@gmail.com
#  secret_key: study-springboot

server:
  port: 9091